language: cpp
compiler: gcc
sudo: required
install: true
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd test
  - ./run_all_test.sh
  - cd ../../python-package
  - sudo apt-get install python3-pip
  - sudo python3 -m pip install setuptools wheel cython
  - sudo python3 -m pip install setuptools wheel cython
  - sudo python3 setup_pip.py sdist
  - sudo python3 setup_pip.py --universal --plat-name manylinux1_x86_64
  - cd ../build/python-package/test/
  - sudo python3 -m pip install scikit-learn cython pandas
  - python3 test_python.py
  - python3 test_data_conversion.py
